/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsTechnologyRouteImport } from './routes/news/technology'
import { Route as NewsSportsRouteImport } from './routes/news/sports'
import { Route as NewsPoliticsRouteImport } from './routes/news/politics'
import { Route as NewsInternationalRouteImport } from './routes/news/international'
import { Route as NewsEconomyRouteImport } from './routes/news/economy'
import { Route as NewsBreakingNewsRouteImport } from './routes/news/breaking-news'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsTechnologyRoute = NewsTechnologyRouteImport.update({
  id: '/news/technology',
  path: '/news/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSportsRoute = NewsSportsRouteImport.update({
  id: '/news/sports',
  path: '/news/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsPoliticsRoute = NewsPoliticsRouteImport.update({
  id: '/news/politics',
  path: '/news/politics',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsInternationalRoute = NewsInternationalRouteImport.update({
  id: '/news/international',
  path: '/news/international',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsEconomyRoute = NewsEconomyRouteImport.update({
  id: '/news/economy',
  path: '/news/economy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsBreakingNewsRoute = NewsBreakingNewsRouteImport.update({
  id: '/news/breaking-news',
  path: '/news/breaking-news',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/news/breaking-news': typeof NewsBreakingNewsRoute
  '/news/economy': typeof NewsEconomyRoute
  '/news/international': typeof NewsInternationalRoute
  '/news/politics': typeof NewsPoliticsRoute
  '/news/sports': typeof NewsSportsRoute
  '/news/technology': typeof NewsTechnologyRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/news/breaking-news': typeof NewsBreakingNewsRoute
  '/news/economy': typeof NewsEconomyRoute
  '/news/international': typeof NewsInternationalRoute
  '/news/politics': typeof NewsPoliticsRoute
  '/news/sports': typeof NewsSportsRoute
  '/news/technology': typeof NewsTechnologyRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/news/breaking-news': typeof NewsBreakingNewsRoute
  '/news/economy': typeof NewsEconomyRoute
  '/news/international': typeof NewsInternationalRoute
  '/news/politics': typeof NewsPoliticsRoute
  '/news/sports': typeof NewsSportsRoute
  '/news/technology': typeof NewsTechnologyRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/news/breaking-news'
    | '/news/economy'
    | '/news/international'
    | '/news/politics'
    | '/news/sports'
    | '/news/technology'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/news/breaking-news'
    | '/news/economy'
    | '/news/international'
    | '/news/politics'
    | '/news/sports'
    | '/news/technology'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/news/breaking-news'
    | '/news/economy'
    | '/news/international'
    | '/news/politics'
    | '/news/sports'
    | '/news/technology'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  NewsBreakingNewsRoute: typeof NewsBreakingNewsRoute
  NewsEconomyRoute: typeof NewsEconomyRoute
  NewsInternationalRoute: typeof NewsInternationalRoute
  NewsPoliticsRoute: typeof NewsPoliticsRoute
  NewsSportsRoute: typeof NewsSportsRoute
  NewsTechnologyRoute: typeof NewsTechnologyRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/technology': {
      id: '/news/technology'
      path: '/news/technology'
      fullPath: '/news/technology'
      preLoaderRoute: typeof NewsTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/sports': {
      id: '/news/sports'
      path: '/news/sports'
      fullPath: '/news/sports'
      preLoaderRoute: typeof NewsSportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/politics': {
      id: '/news/politics'
      path: '/news/politics'
      fullPath: '/news/politics'
      preLoaderRoute: typeof NewsPoliticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/international': {
      id: '/news/international'
      path: '/news/international'
      fullPath: '/news/international'
      preLoaderRoute: typeof NewsInternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/economy': {
      id: '/news/economy'
      path: '/news/economy'
      fullPath: '/news/economy'
      preLoaderRoute: typeof NewsEconomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/breaking-news': {
      id: '/news/breaking-news'
      path: '/news/breaking-news'
      fullPath: '/news/breaking-news'
      preLoaderRoute: typeof NewsBreakingNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  NewsBreakingNewsRoute: NewsBreakingNewsRoute,
  NewsEconomyRoute: NewsEconomyRoute,
  NewsInternationalRoute: NewsInternationalRoute,
  NewsPoliticsRoute: NewsPoliticsRoute,
  NewsSportsRoute: NewsSportsRoute,
  NewsTechnologyRoute: NewsTechnologyRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
